<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tw_yourls"
 *
 * Auto generated by Extension Builder 2015-04-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'YOURLS URL shortener',
	'description' => 'YOURLS URL shortener API client (http://yourls.org)',
	'category' => 'plugin',
	'author' => 'Joschi Kuphal',
	'author_email' => 'joschi@tollwerk.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);